-   id: check-tests-decorator-tag
    name: check decorator funid test
    description: checks if test files have decorator "funid_test"
    entry: check-decorator-value
    language: python
    types: [python]
-   id: check-po-translation
    name: check translation duplicate test
    description: check translation duplicate test
    entry: check-po-translation
    language: python
-   id: check-up-to-date
    name: check branch is up to date
    description: check branch is up to date
    entry: check-up-to-date
    language: python
-   id: check-migration-tools
    name: check migration condition
    description: check if all migration condition are met
    entry: check-migration-tools
    language: python
